/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    IconEpAccessibility: typeof import('~icons/ep/accessibility')['default']
    IconEpAccountBox: typeof import('~icons/ep/account-box')['default']
    IconEpAddLocation: typeof import('~icons/ep/add-location')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilter: typeof import('./src/components/common/searchFilter.vue')['default']
    VoidEmpty: typeof import('./src/components/common/voidEmpty.vue')['default']
  }
}
